2001-06-15  Marcus Brinkmann  <marcus@gnu.org>
	* rc: Merge in recent changes from daemons/rc.sh.

diff --git a/debian/rc b/debian/rc
--- a/debian/rc
+++ b/debian/rc
@@ -1,10 +1,16 @@
 #!/bin/bash
 PATH=/bin:/sbin
 
+# Start the default pager.  It will bail if there is already one running.
+/hurd/mach-defpager
+
+# Set up swap space.  This will complain if no default pager is functioning.
 swapon -a
 
+# Check filesystems.
 if [ -r /fastboot ]
 then
+        # ... or don't.
 	rm -f /fastboot
 	echo Fast boot ... skipping disk checks
 elif [ $1x = autobootx ]
@@ -38,7 +44,7 @@ then
 		;;
 	# Oh dear.
 	*)
-		echo "Unknown error during fsck"
+		echo "Unknown error during fsck (exit status $?)"
 		exit 1
 		;;
 	esac
@@ -129,4 +135,3 @@ chmod 664 /etc/motd
 )
 
 date
-
